components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-20.3.1
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: aaed3363afb9f7298f0e6d02cdc5885b50bc5d3a
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: eaa19ddf81e8b620c7f87ca50230120905e7c679
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 66905b9a5d7b046295ca9c83a94d7e159a46d776
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 18a7db778c3ec50265d3d88810f93892e18fbb2a
    type: git
  level_zero:
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v1.0.13
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: bdce23639f614d7bac6790a74323c0a8f0a3cfe5-1468
converter: M-1468
version: '1'
