components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-20.2.5
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: 3e7c8e95b48a4eb6637077c52ff253a37b5ea085
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: 2dc6dd0ea93b93859cbad55ade61e1bc800ec1fe
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: df8d48f5e352a7340a3dcb58b861a580907d7734
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 18a7db778c3ec50265d3d88810f93892e18fbb2a
    type: git
  level_zero:
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v1.0.13
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: bdce23639f614d7bac6790a74323c0a8f0a3cfe5-1468
converter: M-1468
version: '1'
